spring:
  application:
    name: BankingApp
  datasource:
    url: jdbc:postgresql://pg-21414e-integrarisk.l.aivencloud.com:24105/defaultdb?ssl=require&user=avnadmin&password=AVNS_E70PrGxU-da0dDhl55b
    username: avnadmin
    password: AVNS_E70PrGxU-da0dDhl55b
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect